language: node_js
node_js:
  - "10.9.0"

cache: yarn

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
  - name: Playground UI Pipeline
    env: PACKAGE_LOCATION=packages/app PACKAGE_NAME=jsdocs-codesandbox

script:
  - yarn build
  - cd $PACKAGE_LOCATION

deploy:
  provider: script
  script: now www --token $NOW_TOKEN
  skip_cleanup: true
  app: $PACKAGE_NAME